import copy
import base64
import os
import json
import socket
import struct
import tempfile
import unittest
import zlib

from tests import KERNEL_REFERENCES, schema_matches
from workflow_kernel.provider_dispatch import (
    EXIT_AUTHORIZATION_DECLINED, EXIT_DISCLOSURE_DECLINED,
    EXIT_PROVIDER_FAILURE, EXIT_RESULT_VERIFICATION, EXIT_UNKNOWN,
    EXIT_VERIFIED, FROZEN_EXCHANGE, FROZEN_TRUST_CHAIN, MAX_FRAME_BYTES,
    MAX_REQUEST_BYTES, MAPPING, OPERATION_FAMILY, PRODUCTION_INELIGIBLE_DOMAIN,
    PROTOCOL, SUBSTRATE_AUTHORITY, FIXTURE_ROOT_PUBLIC_KEY, FakeBroker, ProviderDispatchError,
    build_openrouter_body, canonical_json, encode_request, frame32, frame64,
    decode_request, decode_response, deliver_verified_fd3, parse_canonical_json, sha256, signature_input, validate_authority_binding,
    validate_challenge, validate_exchange, validate_fd3, validate_request, validate_result, validate_status,
    verify_terminal_result,
)


REQUEST_SCHEMA = KERNEL_REFERENCES / "provider-dispatch-request-schema.json"
RESULT_SCHEMA = KERNEL_REFERENCES / "provider-dispatch-result-schema.json"
STATUS_SCHEMA = KERNEL_REFERENCES / "provider-dispatch-status-schema.json"
EXCHANGE_SCHEMA = KERNEL_REFERENCES / "provider-dispatch-exchange-schema.json"
D = "sha256:" + "1" * 64
ROOT_D = int("87ada8c1b7a07e3c423e657645d02e2ffb8fd6db8f0db87d451dd57894ccb81a6f15ce5371be54f67c6efcaf300c0831a0c86633b774c0b17f3cdb305ab31061ae4c7e51fdccd2b03e7911f88ab7684aab332d561e3a84b8ca68da3b4bfadfec4cee011628e77ec98aa570d655bd36ae8c40399d431d9ac64f854045fe57881", 16)
RESULT_N = int("b3f92ef0a7d361a25719124dee17407c05508be29ae7c916ebb68544cf71e61a403adc6372598f4b797d21567e88f6550077fa36acc769822ec814f0d05cc274d0ec6aecfb7a4bbce97d036e8467ea61eff01b21a4a411639f9ac4252d101c5e9d9b8de98c576b7e96c79eb68fa8a4646bdfe1213c1d8c51912f2e875d72bd1d", 16)
RESULT_D = int("14a6a31c3a25a72e599026e98a4860bdda5e43aedcd77bdb85708c1a39337893ca8af67ef2c0141134ff86b3c6113132cfbaf49b11785042ffdb358bec5cb8733d9fb09b570c73a50c35f3a24966d89f475572406ef3db11f280aa28cb57c981f84b69c6c40b9f95c102e4a778d5962e8502addfdb755799b3b031a9e7f83e81", 16)
RESULT_PUBLIC_KEY = f"fixture-rsa-sha256-v1:{RESULT_N:0256x}:10001"

# Independently checked-in compressed base64 of the harmless accepted vector.
# These bytes are not generated by the producer under test.
LITERAL_COMPONENTS = {
    "request": "eNq1VEtu3DAMzaJogaCHKLyOY9kz498lWqBZNS0MWaLHQm1JleRJpsHcoD1Dr9gjlLQnHyTpKog2EkXiiXx81MnJ2zc3EZ9Cb5wK+6i+iVpjQqNkVM+nmKXRWSSM1iCCMrrRRgtofM+zTY4xy6FOX7jwDclhRPx2UoN8DXy4tsqBb3hA2IxleczKmK0uGKtZVjP2BWOU9xPIZ0PYMWSuH93zvrBjzaDE/jVytk4Z14ieK91ItQUf7uFXL1wI7wXHvrrX49zDjwlmvgoyvCcFzdo6GkTgAXuPlSnNSWDo60Owvk4SY0E7MwVw51wh2qBGFTxpdOTXjeWODMz0bLFBS6W3uLtm0VJU5+unPgvgovoZhwNrvArG4RikR1BHBfjQtPsA+Fi5Ksuclbc+b4328Mh5IK+1iIql3JcQYxdDvCNWRsBxIxI+ffx8QbaRMCDA5RzOVbK1Id6c5+j6GZM5jGhm0bczCnAzTU3HRzVgpqhrRNd8aKwzOyWpeuUtD6InAS0kXd7QCAfQoRlAb0M/N+T26nHjKwCRlVhMt05TqIq2XBUsb1kJUEi8lkxCVUmZteW6KkEAL/MMvSkTnSjSDN91ZqAh8XsfYMQOP30/zf6fAOJ2ICoBLBdp2hXrDQexKVYiZx2TueyKVZnzQvAVk7zabNq8ghLKVHQVx/zK+wQmj80+fCMi6NEo4VYluzShZiTCjHYAYtPPs2aCEWbAqCvjvneDuYrvPsb4ltz4ltyllV70MPJmB87P2k3pCptEIsXhkkryQHncnZcfY+CabrmnMRiRAsr4gfxoINRWxyMXvdLgE4nOOWg6zg8eFijKdTCc7qyyMGB4/AAX1ein1gdUDTQP/nn8v0JDcS6AjA4ny3q3NOz0aL4n+j78/fPr99fo9B/STNiJ",
    "challenge": "eNq1Vs1y3DYMzrHPobPlJSn+7ku0M82pnY4GJEEvJ1pJFSXHbsbP0lctKDl2Jk5OaTSzK4IAP4Ig8EHv3v3y76cGtvUyLXl97KEUXNY8jc35UxOnK2QaNSk/rNuCtx+n5UMapo/ty4LbPN7DkGNz03zIY3y1bZcCbbmAULq956Qmsw2/pz9zxnyXTOxE5zym0DGlnGad0jFExjvpIWinLf2QC87B64CcR6clBKmY5NFGpoSX0qrY6SScSqiiAcYYoFZc+qgYCGGcd5KryLnQnPsQIUm0SekkO6GTY9IL74032nedAmO6GBPhIGcSDIbQWW0tsM4JY5DU3EQbbAcenfdJJo6eVBCZtYIpy5NAowUwRydknnRoAySRrOY6WhkNdxyap5vGT9Pa5xrDOmpZjVqYxhFDvZB+nMaA/REysjkGZ/6DD+0RAa+E77c8xJ+Cj2XNIxxZ1VzWdS7n02macVymbcXlFjJZ4cOcFyw9rGQkmNAtsy3r3jN2ZuLM2B9kk0vZMH7ThD2bDPma11Kz9woP/QxLFeggN4eMY8zjHb2X/jh2c9byrW5GXJrzNxQLzlPJ67Q8Nmf+DLrg3xsdsfePK9JmtrNWM/tZV+ZpLPiV8qlq55lQ6SSvkWjDBdajXK5IFVZz4bdff39f5SniQAB/7uaQT3fz2qpbTap/2ioOVxJF89dNsycKrdzfRxrRmmW/gD7BNQ/kPMWbNhxh6Odlus+xBiSXGdZwIXt6X8jmBHM+3fNTdesUpus8YAUp1QJrmGq2UtnwZ3mrsmJVnIYcHn9GNs1LnpaePMojeXxHgX+F737w2eGndQrTQKBv2a79HKv2c6yOy3rJgCm+PbM2IaSgMCKiJuKQXKDT4IxVXMioopJWaAhEORKNTJI5yw1znv4E8eKOX7Zh7Uu+G2te/s/MPG+eLqv/gI/fpWfiZuKtxIAYWnOaraRFziNyI5kJxNbMehQO0ATHNXqvrZIyJMORFkjWQQy6M0I5m6Q3zkTBlTZobdK0mBmToKMoBKOdFQKD5TIxovQQhJGRYdCAIXkD0vuAtJ51Gq0kCNAcU2LcC9oIJOe6c8lRWxBKRM44xd5F521EZ4MiXjcU/2Acko8JLEgttY+p9pUuUB8Jqh6OaNsaaiDCRx5rf6JCorItAYiRl5/HliVc8Ar9PS5lJ0xep6h+67XT3jFHWGt1v4yPCh9grLO1f5dyxXHd0+aVrCoLU/q0VwiXPGI5RVLuRtt4NB0aHFA1l4YJ6tycZxzIvP0Ctwah5vtOMqYKpXp6gDwLB1DZfFmJd7B/ycqdltbnzwysyUkGY4Gjxe0QX0xUmKf/AE1fljM=",
    "ack": "eNoljFsKwyAURLMWvyNE4zObCVZvq8RqUJsQSlfWzVXo3wxz5gzD8H0j602MkB6wVm8oF2hB/7BMs1AOBGPSMSE0V1KrG2cAMDFJwTE1aRCSdwIoVTPhTCnam7NcO6LQiPaSW7Y5dumZy3aP+cTm1XwuoV24r0dwULALdTfNenyQfqrWw9OsB5QackILGVG7dugOm1OF1FZjN/T5ARx3PAI=",
    "content": "eNpjYAAD7mql/Gwlq5Ki0tRaABdvBBw=",
    "terminal": "eNqlVcmS2zYQ9SkfwvNwjH3RPX+QU1IpVgNojFCmAIaLPBNX/j0NyTN2POVTJBWLaPTygPe69eHDL79+GeDYz20t+8sE24brXlqdtjMIbYbTcH85MYXgEKMSSeccrUlRBWlj5sl5yVEoraNR2hmRgVyMzCAYdzwp52w2w8MQzzDPWJ/wfXJpXEKjlE3KGK+d9S5ohYhMWYGUgnk0VpMHCuEk15RU0CpF7RN3PfmMUI9lOH0ZYqsVYz8FVYhz2zB1h1Z3rPsUjpxxpZ1Utghrum2uSOe+wmtMq9txoY1/ethlmXHHNMFOW4IJMzI3MvkbY6f+k79TPD6XfYot4XBiD0PZtuPnAawHXMh33obTH0NbsEL5+LTso37s1/T32JfzhZZi+POhO6w3ZFOGS5lfKCk+77hWmKdlbdeScJ3oMAvs8Uzx7dgJNCEZrriWXG4HXGDtAI9KmAQt19LWiQgplUKfcNu/kSH/56dXW9veYpsp6ee2fspz+zy+iWx8BT2+gh6v/B50M1NQv5OVzkGLzs1fBwGcQksv75RjbIw5akykFeOAKS7QG/DWaS5U0omUIgxEG6xCq7Ji3nHLfKCH4IzduV+IcJy6NvfzcOL8O+OPBRUzJEjIVrMcHOtZ0Ulk0TPholcohSIgLpjMDVfWKikcZqY0pwgv7wWPeZ+28lSJuR8LWIDEmGfOmygFumRiMkFL4CZpp20UQJkic9al4L2gVmOQrBLgopHcUoEtnvECE9G/3QTNu4nu9NYcUFNJsHd9vL2PrBMwQ+3WPgO27UK9csO6tK3sbe2yS9gxjxeI51Jx+5ho8+Z01KkkcqCXe6rO+tyg25ay4Ezu43d5qa82nKlHqUtunfCV8//0wdZ5r5EgWVpQYdiP9XaG1C4kXIrJ5bnbHt+L7LHUK8ylS/9Tqemb77huMN6v+i47cjvwZ/snHWl6iZByTD7yzCR3UmmfaeY5hyYqxkCR6pyWCaKgQYVZZh681BYk40wDB0XTKjCwyI2FIL1nnCP3UTkeg2JOpRwsZ9x7n5WMiYYpzT0N2hKv6IJ0XCrDvSA1aQiQUYeMmcKVdS5mH1AzFUEam7UiEImGaRRBykylgrOcshJGKpySNWBC4pysSEISKgpJX4IcaZ4DIcDAtMYYSLHyRtURtp1GEE5v10v3Vdv+9e+iD8p/AcMY68c=",
    "challenge_input": "eNq1VV1v5SYQzW/xc5wLGAP2n2il7lOrysIwvhfFBhfwTdJo/3sHOx+rJvu0ih9sBg6HmeHM+CHE+2kOD7Xe8iVEl59u1hiuzkKsrUurzuZSX+mNueh5Bn+Gm+dqDCEPzlb9PqoJrW4rE7wHk13wgw/ewJAumrUCMcegp7/44BlWw4L84+Zm+yX8kLLzugSBvJec19SfTmEFH8OWId5phyh4XF2ENOiMIEaYqImqSfONkJ6wnpA/EeNS2sB+CiEvkNktLqeqf64W/TisOhYDA7k9bPDW+TN+43CEXfWCf1xbAWLVf7IQYQ3J5RCfqp6+kEb4Z8MQh/EpAx6mGqUEUa9raQ0+wf8Wv5fVdUVWjOQ9EzXKIaMsMI4FUDdFC7//9se3YgcLMxL8tcO1O53XXLd3Apf+rYs5L2iy6u/bahcK7ty/h4xwT9wvYJj04mZ0HvONB3o9D6+6HF51iXj8XhBz0qs7XempuHUyYVlnKCSpIKCkqaiVN4y+2FuxW1LMMDvz9BVqWqMLcUCPnEePz5j4d/rmF5+dPuRgwoykDx9quP6shnHTmwKC/RizkMZMpgULAEJpwimDTuhOqpYyblvbcsWENnKUHCSfOOkUlaQb8cUoITt/2uY8JHf2RZfPlQ0Lxo9nTO4xbxHuPvp65/xVz3ght9W98/YdW8ek68O3w/t1G/Gyhnt4+hmoH5upYzARLW0jKM5K2hXnAajkRBrStkSNwDoN0nRUwDgK1XJuJkkBN3DSaGtEI1nbqYmPspOW0VZIUGoSuJlIOekGs2Ck6BRjYBTlE7GkNYZJbgkYocFMo9R8HA3gftIIUBwptKAwTYSODA/SnFLRdFOnDWcts5RQzH1nu1FZ6JRppRgl5t/IDtDHSSvNBRejnYAy2hhqEVOCmxgo2VrJRkttj/eAhYRlm4zGjhy/rlsmc4FFD1eIaW+YtExh/ZZrx7OtszqX6n4bHxU+a19mdUqQ0gI+77J5b1alC6N86kWbi/OQThYXd9Dmj58ODg6qoqU56DK3uhVmhNc/8JYkFL3vTUYWIxVPD5IX4yBK25gy9h0Y3lS5t6U8FLqYoYgTAT7p4xe3U/wwUWi+/wfV7zQc",
    "terminal_input": "eNqlVNty3SAMzLf4OW4Ac/P5jj610/FgEDlMbXAB59JM/73CJ0nTpn2qx+NBQisJduX7lL/6Jd33Zq/nlEN9vNpyugsOcu9C2Uy15/6OXlXIa4hmuXrqXiMnUwrkGlKcytkwIbtTd1mcCAejASxnTnhvlXSWz4Oynjo9DhQYF8JKLrRk3mCIHLxhhGrquNbKy+66s2ezLBBv4X3yQWoHknPluJSj0GrUs+AAQLhigCnICFIJjADG9EAFJmVoOStGR3VLvoCJ+9adnjqbYgTbToEV7JIKuBaQYoVYp3n3HjLu4GVYk92xmQHPfWdeMCmWfcWNHw22bgtUcJOpuMUIkz3RPRk+EnJq7/AJ8fAQ6mSTg+5ErrtQyv5vAGmAFWOX0p0+d2mDaMLN7VZ78aFd0/e+mcuKJuu+XLeAfHQ2ebOG5RGTwgOyh9xNL8xOL8wiPu0Vm8ZOujvIwYfjgJvJrcE9Yk8MzRxSnpCQEBF6C6X+ImP4z6dVy6kmmxZMev9Ojv3f5HgBHW4EtTvJeA40GjffdmxwmpN7fKccqaz1VoBDrUhtCKcMRmlGpQVl3AmHSmHSWDUrDop7TkZNFRln/DBKyIX7DQmHqWmznrsTpW+cfxbkRKIgjVeC+FmTlhX0AMSOhGk7chgYx0b0LD2VlCvFB6bBEy4oIsbhUnBf6lTCbUTm/iygjHGEjESP0g4MtJPWyVkMhkontFCWGcxkiVbazePIcNSIcYozo60cqMICxZ5hNRPSXw5B0+bCOz2Gw0QXnKlNH6/rnjQCFhObt/0DSllxVo5et1RCTbnJzkHruV+NPYcI5cbh5hG0xyk4DMDFJVVjfUmm+bawwYLh/Zu8OFcFFpxRnJJjEp45/20OSuM9WmxJobHPpeIYwPSqI8TEVJ9/WW1YfwJqz495",
}


def fixture_sign(modulus, private_exponent, payload):
    digest = int.from_bytes(__import__("hashlib").sha256(payload).digest(), "big")
    return f"fixture-rsa-sha256-v1:{pow(digest, private_exponent, modulus):0256x}"


def limits():
    return {
        "max_request_bytes": 8388608, "max_response_bytes": 8388608,
        "max_parts": 256, "max_pending_per_peer": 4,
        "max_pending_per_repository": 16, "max_pending_per_daemon": 64,
    }


def scope():
    return {
        "repository": "design-machines/depot", "run_id": "run-01",
        "lane": "assessment", "candidate": "candidate-01",
        "workload": "pipeline-assessment",
    }


def request(parts=(b"system\n", b"user \xf0\x9f\x8c\x8d\\\"\n"), roles=("system", "user")):
    return {
        "schema_version": 1, "protocol": PROTOCOL, "mapping": MAPPING,
        "operation_family": OPERATION_FAMILY,
        "substrate_authority": SUBSTRATE_AUTHORITY,
        "destination": "https://openrouter.ai", "method": "POST",
        "path": "/api/v1/chat/completions",
        "models": ["openai/gpt-5.6", "z-ai/glm-5.2"],
        "parts": [
            {"role": role, "content_length": len(raw), "content_sha256": sha256(raw)}
            for role, raw in zip(roles, parts, strict=True)
        ],
        "scope": scope(),
        "authority": {
            "daemon_build_sha256": D, "scanner_build_sha256": D,
            "policy_sha256": D, "nonce": "nonce-01", "sequence": 7,
            "boot_id": "boot-01", "session_id": "session-01",
            "connection_nonce_sha256": D,
            "prior_chain_digest": "sha256:" + "3" * 64,
            "issued_at": "2026-08-03T00:00:00Z",
            "expires_at": "2026-08-03T00:02:00Z",
        },
        "limits": limits(),
    }


def challenge(req, body):
    authority = req["authority"]
    document = {
        "schema_version": 1, "protocol": PROTOCOL, "mapping": MAPPING,
        "operation_family": OPERATION_FAMILY,
        "substrate_authority": SUBSTRATE_AUTHORITY,
        "transaction_id": "transaction-01",
        "connection_nonce_sha256": authority["connection_nonce_sha256"],
        "peer_uid": 501, "peer_pid": 4321,
        "request_body_sha256": sha256(body),
        "destination": req["destination"], "method": req["method"],
        "path": req["path"], "models": req["models"], "scope": req["scope"],
        "daemon_build_sha256": authority["daemon_build_sha256"],
        "scanner_build_sha256": authority["scanner_build_sha256"],
        "policy_sha256": authority["policy_sha256"], "nonce": authority["nonce"],
        "sequence": authority["sequence"], "boot_id": authority["boot_id"],
        "session_id": authority["session_id"], "issued_at": authority["issued_at"],
        "expires_at": authority["expires_at"], "limits": req["limits"],
        "result_signer": {"kind": "fixture-rsa-sha256-v1", "domain": PRODUCTION_INELIGIBLE_DOMAIN, "public_key": RESULT_PUBLIC_KEY},
        "authority_assertion": {"kind": "fixture-rsa-sha256-v1", "domain": PRODUCTION_INELIGIBLE_DOMAIN, "value": "fixture-rsa-sha256-v1:" + "0" * 256},
        "prior_chain_digest": authority["prior_chain_digest"],
    }
    document["authority_assertion"]["value"] = fixture_sign(
        int(FIXTURE_ROOT_PUBLIC_KEY.split(":")[1], 16), ROOT_D,
        signature_input("challenge", document),
    )
    return document


def result(req, chall, response=b'{"ok":true}'):
    document = {
        "schema_version": 1, "protocol": PROTOCOL,
        "operation_family": OPERATION_FAMILY,
        "substrate_authority": SUBSTRATE_AUTHORITY,
        "outcome": "verified", "exit_code": 0,
        "request_body_sha256": chall["request_body_sha256"],
        "response_sha256": sha256(response), "response_length": len(response),
        "part_count": len(req["parts"]), "models": req["models"],
        "selected_model": req["models"][0], "provider": "openrouter",
        "scope": req["scope"], "sequence": req["authority"]["sequence"],
        "issued_at": req["authority"]["issued_at"],
        "completed_at": "2026-08-03T00:00:03Z",
        "challenge_sha256": sha256(canonical_json(chall)),
        "authority_assertion_sha256": sha256(canonical_json(chall["authority_assertion"])),
        "result_signer_sha256": sha256(canonical_json(chall["result_signer"])),
        "prior_chain_digest": req["authority"]["prior_chain_digest"],
        "cleanup": {"reservation": "consumed", "connection": "closed", "content_buffer": "discarded"},
        "signature": {"kind": "fixture-rsa-sha256-v1", "domain": PRODUCTION_INELIGIBLE_DOMAIN, "value": "fixture-rsa-sha256-v1:" + "0" * 256},
    }
    document["signature"]["value"] = fixture_sign(
        RESULT_N, RESULT_D, signature_input("terminal", document),
    )
    return document


class ProviderDispatchContractTests(unittest.TestCase):
    """REQ-M0-01..11 and stable CHK-M0 vectors."""

    def setUp(self):
        self.parts = (b"system\n", b"user \xf0\x9f\x8c\x8d\\\"\n")
        self.request = request(self.parts)
        self.body = build_openrouter_body(self.request, self.parts)
        self.challenge = challenge(self.request, self.body)
        self.ack = {
            "schema_version": 1, "protocol": PROTOCOL, "type": "consent_ack",
            "challenge_sha256": sha256(canonical_json(self.challenge)),
        }
        self.response = b'{"ok":true}'
        self.result = result(self.request, self.challenge, self.response)

    def test_req_m0_01_request_and_challenge_bind_every_authority_field(self):
        validate_request(self.request, self.parts)
        validate_authority_binding(self.request, self.body, self.challenge, self.ack)
        for field in (
            "repository", "run_id", "lane", "candidate", "workload",
        ):
            mutation = copy.deepcopy(self.challenge)
            mutation["scope"][field] += "-changed"
            with self.subTest(field=field), self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
                validate_authority_binding(self.request, self.body, mutation, self.ack)

    def test_req_m0_02_result_is_structurally_content_free(self):
        self.assertEqual(validate_result(self.result), self.result)
        forbidden = {"content", "prompt", "response", "credential", "api_key", "socket_path"}
        self.assertTrue(forbidden.isdisjoint(self.result))
        self.assertTrue(schema_matches(self.result, json.loads(RESULT_SCHEMA.read_text())))
        self.assertTrue(schema_matches(self.request, json.loads(REQUEST_SCHEMA.read_text())))

    def test_req_m0_03_dispatch_never_asserts_repository_substrate(self):
        for document in (self.request, self.result, self.challenge):
            self.assertEqual(document["operation_family"], "external_provider_dispatch")
            self.assertEqual(document["substrate_authority"], "not_asserted")
            self.assertNotIn("repository_verification", canonical_json(document).decode())

    def test_req_m0_04_openrouter_mapping_preserves_exact_order_and_text(self):
        expected = b'{"messages":[{"content":"system\\n","role":"system"},{"content":"user \xf0\x9f\x8c\x8d\\\\\\\"\\n","role":"user"}],"models":["openai/gpt-5.6","z-ai/glm-5.2"],"temperature":null}'
        self.assertEqual(self.body, expected)
        self.assertIn(b'"temperature":null', self.body)
        self.assertNotIn(b'"provider":null', self.body)
        null_parts = (b"null", b"line1\nline2")
        mapped = build_openrouter_body(request(null_parts), null_parts)
        self.assertIn(b'"content":"null"', mapped)
        self.assertIn(b'"content":"line1\\nline2"', mapped)

    def test_req_m0_05_signature_projection_is_domain_separated_and_complete(self):
        terminal_input = signature_input("terminal", self.result)
        self.assertTrue(terminal_input.startswith(b"workflow-authority\x00provider-dispatch-v1\x00terminal\x00"))
        self.assertNotIn(b'"signature"', terminal_input)
        for marker in (b'"scope"', b'"challenge_sha256"', b'"authority_assertion_sha256"', b'"cleanup"'):
            self.assertIn(marker, terminal_input)

    def test_req_m0_06_fake_is_explicitly_production_ineligible(self):
        fake = FakeBroker("/tmp/provider-dispatch-test/socket")
        status = fake.status()
        self.assertFalse(fake.production_ready())
        self.assertFalse(status["production_ready"])
        self.assertEqual(status["fixture_domain"], PRODUCTION_INELIGIBLE_DOMAIN)
        self.assertTrue(schema_matches(status, json.loads(STATUS_SCHEMA.read_text())))
        for path in ("/run/workflow-authority", "/var/run/workflow-authority", "relative"):
            with self.subTest(path=path), self.assertRaises(ProviderDispatchError):
                FakeBroker(path)

    def test_req_m0_07_mutations_unknowns_malformed_and_bounds_reject(self):
        mutations = []
        for field in ("mapping", "destination", "method", "path", "operation_family", "substrate_authority"):
            item = copy.deepcopy(self.request); item[field] += "-changed"; mutations.append(item)
        item = copy.deepcopy(self.request); item["unknown"] = True; mutations.append(item)
        for mutation in mutations:
            with self.assertRaises(ProviderDispatchError):
                validate_request(mutation, self.parts)
        bad_parts = list(self.parts); bad_parts.reverse()
        with self.assertRaisesRegex(ProviderDispatchError, "part_frame_mismatch"):
            validate_request(self.request, bad_parts)
        changed_models = copy.deepcopy(self.challenge); changed_models["models"].reverse()
        with self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
            validate_authority_binding(self.request, self.body, changed_models, self.ack)

    def test_req_m0_08_public_diagnostics_never_echo_hostile_text(self):
        hostile = b'{"secret":"sk-fixture-do-not-echo","secret":1}'
        with self.assertRaises(ProviderDispatchError) as caught:
            parse_canonical_json(hostile)
        self.assertEqual(str(caught.exception), "invalid_document")
        self.assertNotIn("fixture", str(caught.exception))

    def test_req_m0_09_complete_positive_vector_bytes_are_frozen(self):
        request_bytes = encode_request(self.request, self.parts)
        challenge_bytes = frame32(canonical_json(self.challenge))
        ack_bytes = frame32(canonical_json(self.ack))
        content_bytes = frame64(self.response)
        terminal_bytes = frame32(canonical_json(self.result))
        vector = request_bytes + challenge_bytes + ack_bytes + content_bytes + terminal_bytes
        self.assertEqual(struct.unpack(">I", request_bytes[:4])[0], len(canonical_json(self.request)))
        self.assertEqual(sha256(vector), "sha256:44f32594ffcc189edadf71bc0ea51131c72cdb1158f8f065672962b7d4790343")
        self.assertEqual(EXIT_VERIFIED, 0)
        self.assertEqual(FROZEN_EXCHANGE["fd3"]["kind"], "inherited-anonymous-pipe")
        self.assertFalse(FROZEN_EXCHANGE["retrieve"])
        fake = FakeBroker("/tmp/provider-dispatch-test/socket")
        self.assertEqual(
            fake.complete_exchange(
                self.request, self.parts, self.challenge, self.ack,
                self.response, self.result,
            ),
            vector,
        )

        golden_variants = {}
        for name, parts, roles, response in (
            ("null", (b"null", b"line1\nline2"), ("system", "user"), b"null"),
            ("max", (b"x" * MAX_FRAME_BYTES,), ("user",), b"x" * 8388608),
        ):
            req = request(parts, roles)
            body = build_openrouter_body(req, parts)
            chall = challenge(req, body)
            ack = {
                "schema_version": 1, "protocol": PROTOCOL, "type": "consent_ack",
                "challenge_sha256": sha256(canonical_json(chall)),
            }
            terminal = result(req, chall, response)
            golden_variants[name] = sha256(FakeBroker(f"/tmp/{name}/socket").complete_exchange(
                req, parts, chall, ack, response, terminal,
            ))
        self.assertEqual(golden_variants, {
            "null": "sha256:7a1e18de6859c5e2870e67260a60cfad97d521619aa0235b02f1166ccb2208cc",
            "max": "sha256:69fcc0e8f09c3d57b1079a4babc26f02a9c93f9305db1394ae5bb89ea26d3bf4",
        })
        self.assertEqual(
            sha256(signature_input("terminal", self.result)),
            "sha256:7fdc8e458736906ae0eb3d0342a867b8a5836ee978f94939e6896f41eff78e96",
        )
        literal = {
            name: zlib.decompress(base64.b64decode(encoded))
            for name, encoded in LITERAL_COMPONENTS.items()
        }
        produced = {
            "request": request_bytes, "challenge": challenge_bytes,
            "ack": ack_bytes, "content": content_bytes, "terminal": terminal_bytes,
            "challenge_input": signature_input("challenge", self.challenge),
            "terminal_input": signature_input("terminal", self.result),
        }
        self.assertEqual(produced, literal)
        self.assertEqual(decode_request(literal["request"]), (self.request, self.parts))
        self.assertEqual(
            decode_response(
                literal["content"] + literal["terminal"], self.request,
                self.challenge, fixture_trust=True,
            ),
            (self.response, self.result),
        )
        self.assertEqual(self.result["exit_code"], EXIT_VERIFIED)

    def test_req_m0_09_literal_negative_byte_mutations_have_stable_codes_and_exits(self):
        literal = {
            name: zlib.decompress(base64.b64decode(encoded))
            for name, encoded in LITERAL_COMPONENTS.items()
        }
        cases = (
            (literal["request"] + b"x", "exchange_trailing_data", 2),
            (literal["request"][:-1], "part_frame_mismatch", 2),
        )
        for mutation, expected_code, expected_exit in cases:
            with self.subTest(code=expected_code), self.assertRaises(ProviderDispatchError) as caught:
                decode_request(mutation)
            self.assertEqual((caught.exception.code, expected_exit), (expected_code, 2))
        ack_raw = literal["ack"][4:]
        ack = parse_canonical_json(ack_raw)
        ack["challenge_sha256"] = D
        with self.assertRaisesRegex(ProviderDispatchError, "consent_connection_invalid"):
            validate_authority_binding(self.request, self.body, self.challenge, ack)

    def test_req_m0_10_cross_connection_stale_build_policy_and_result_mismatch_reject(self):
        cases = {}
        for field in ("connection_nonce_sha256", "daemon_build_sha256", "scanner_build_sha256", "policy_sha256"):
            mutation = copy.deepcopy(self.challenge)
            mutation[field] = "sha256:" + "2" * 64
            cases[field] = mutation
        for name, mutation in cases.items():
            with self.subTest(name=name), self.assertRaises(ProviderDispatchError):
                validate_authority_binding(self.request, self.body, mutation, self.ack)
        mismatch = copy.deepcopy(self.result); mismatch["response_length"] += 1
        with self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
            verify_terminal_result(self.request, self.challenge, self.response, mismatch, fixture_trust=True)

    def test_req_m0_11_hmac_envelope_and_receipt_key_downgrades_are_absent(self):
        frozen = canonical_json(FROZEN_TRUST_CHAIN)
        for rejected in (b"authority-envelope-v1", b"hmac", b"receipt-key"):
            self.assertIn(rejected, frozen)
        for document in (self.request, self.challenge, self.result):
            self.assertTrue({"auth_mode", "receipt_key", "hmac"}.isdisjoint(document))

    def test_chk_m0_02_canonical_json_boundaries(self):
        self.assertEqual(parse_canonical_json(canonical_json(self.request)), self.request)
        cases = (
            b'{"a":1,"a":2}', b'{"n":1.0}', b'{"n":NaN}', b'{"n":01}',
            b'{"a": 1}', b'\xff', b'[' * 17 + b'0' + b']' * 17,
        )
        for raw in cases:
            with self.subTest(raw=raw[:20]), self.assertRaises(ProviderDispatchError):
                parse_canonical_json(raw)
        with self.assertRaisesRegex(ProviderDispatchError, "frame_too_large"):
            parse_canonical_json(b" " * (MAX_FRAME_BYTES + 1))
        hostile_integer = b'{"value":' + b"9" * 5000 + b"}"
        with self.assertRaises(ProviderDispatchError) as caught:
            parse_canonical_json(hostile_integer)
        self.assertEqual(str(caught.exception), "invalid_document")
        self.assertNotIn("digit", str(caught.exception))

    def test_chk_m0_03_negative_vector_codes_and_state_outcomes(self):
        expected = {
            "disclosure_decline": (EXIT_DISCLOSURE_DECLINED, "disclosure_declined", False, True),
            "fido_decline": (EXIT_AUTHORIZATION_DECLINED, "authorization_declined", False, True),
            "operator_expiry": (EXIT_AUTHORIZATION_DECLINED, "authorization_expired", False, True),
            "provider_timeout_after_send": (EXIT_UNKNOWN, "provider_result_unknown", True, True),
            "response_mismatch": (EXIT_RESULT_VERIFICATION, "result_verification_failed", True, True),
            "close_before_ack": (EXIT_AUTHORIZATION_DECLINED, "consent_connection_invalid", False, True),
            "close_after_send": (EXIT_UNKNOWN, "provider_result_unknown", True, True),
            "cross_connection_reuse": (EXIT_AUTHORIZATION_DECLINED, "authorization_replayed", False, True),
            "provider_failure": (EXIT_PROVIDER_FAILURE, "provider_failure", True, True),
        }
        self.assertEqual(set(expected), {
            "disclosure_decline", "fido_decline", "operator_expiry",
            "provider_timeout_after_send", "response_mismatch", "close_before_ack",
            "close_after_send", "cross_connection_reuse", "provider_failure",
        })
        for exit_code, code, network, consumed in expected.values():
            self.assertIn(code, FakeBroker("/tmp/fake/socket").status(code)["last_error_code"])
            self.assertIs(type(network), bool); self.assertTrue(consumed)
            self.assertIn(exit_code, {71, 72, 73, 74, 75})

    def test_chk_m0_04_exchange_tombstone_is_nonretrievable(self):
        exchange = {
            "schema_version": 1, "protocol": PROTOCOL, "state": "tombstone",
            "request": self.request, "request_body_sha256": sha256(self.body),
            "challenge": self.challenge, "consent_ack": None, "result": None,
            "safe_error": "consent_connection_invalid", "consumed": True,
            "network_attempted": False, "response_retrievable": False,
        }
        self.assertEqual(validate_exchange(exchange), exchange)
        mutation = copy.deepcopy(exchange); mutation["response_retrievable"] = True
        with self.assertRaisesRegex(ProviderDispatchError, "exchange_state_invalid"):
            validate_exchange(mutation)

    def test_chk_m0_05_flood_rejects_before_response_allocation(self):
        oversized = request(parts=(b"x",), roles=("user",))
        oversized["parts"] = oversized["parts"] * 257
        with self.assertRaisesRegex(ProviderDispatchError, "bounds_exceeded"):
            validate_request(oversized)
        with self.assertRaisesRegex(ProviderDispatchError, "frame_too_large"):
            frame64(b"x" * (MAX_REQUEST_BYTES + 1))

    def test_chk_m0_06_max_legal_part_and_request_budget(self):
        raw = b"x" * MAX_FRAME_BYTES
        req = request(parts=(raw,), roles=("user",))
        body = build_openrouter_body(req, (raw,))
        self.assertLessEqual(len(body), MAX_REQUEST_BYTES)
        self.assertEqual(len(encode_request(req, (raw,))), 4 + len(canonical_json(req)) + 8 + len(raw))

    def test_chk_m0_07_producer_and_parser_use_literal_component_frames(self):
        self.assertEqual(frame32(b"{}"), b"\x00\x00\x00\x02{}")
        self.assertEqual(frame64(b"ok"), b"\x00\x00\x00\x00\x00\x00\x00\x02ok")
        wire = encode_request(self.request, self.parts)
        decoded_request, decoded_parts = decode_request(wire)
        self.assertEqual(decoded_request, self.request)
        self.assertEqual(decoded_parts, self.parts)
        with self.assertRaisesRegex(ProviderDispatchError, "exchange_trailing_data"):
            decode_request(wire + b"hostile")
        truncated = wire[:-1]
        with self.assertRaisesRegex(ProviderDispatchError, "part_frame_mismatch"):
            decode_request(truncated)
        response_wire = frame64(self.response) + frame32(canonical_json(self.result))
        decoded_content, decoded_terminal = decode_response(
            response_wire, self.request, self.challenge, fixture_trust=True,
        )
        self.assertEqual((decoded_content, decoded_terminal), (self.response, self.result))
        with self.assertRaisesRegex(ProviderDispatchError, "exchange_trailing_data"):
            decode_response(response_wire + b"hostile", self.request, self.challenge, fixture_trust=True)

    def test_chk_m0_08_fixture_crypto_rejects_root_terminal_and_provenance_mutations(self):
        verify_terminal_result(self.request, self.challenge, self.response, self.result, fixture_trust=True)
        challenge_mutation = copy.deepcopy(self.challenge)
        challenge_mutation["authority_assertion"]["value"] = "fixture-rsa-sha256-v1:" + "0" * 256
        with self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
            verify_terminal_result(self.request, challenge_mutation, self.response, self.result, fixture_trust=True)
        for field, value in (
            ("signature", {"kind": "fixture-rsa-sha256-v1", "domain": PRODUCTION_INELIGIBLE_DOMAIN, "value": "fixture-rsa-sha256-v1:" + "0" * 256}),
            ("selected_model", "attacker/model"), ("provider", "attacker"),
            ("prior_chain_digest", D),
        ):
            mutation = copy.deepcopy(self.result); mutation[field] = value
            with self.subTest(field=field), self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
                verify_terminal_result(self.request, self.challenge, self.response, mutation, fixture_trust=True)
        cleanup = copy.deepcopy(self.result); cleanup["cleanup"]["reservation"] = "closed"
        with self.assertRaises(ProviderDispatchError):
            validate_result(cleanup)

    def test_chk_m0_09_stateful_fake_owns_connection_consumes_and_tombstones(self):
        fake = FakeBroker("/tmp/stateful/socket")
        tx = fake.reserve("connection-1", 501, self.request, self.parts, self.challenge, "2026-08-03T00:00:01Z")
        with self.assertRaisesRegex(ProviderDispatchError, "consent_connection_invalid"):
            fake.acknowledge(tx, "connection-2", self.ack, "2026-08-03T00:00:02Z")
        self.assertEqual((fake.fido_attempts, fake.network_attempts, fake.response_allocations), (0, 0, 0))
        fake.acknowledge(tx, "connection-1", self.ack, "2026-08-03T00:00:02Z")
        fake.mark_sent(tx, "connection-1")
        fake.finish(tx, "connection-1", self.response, self.result)
        self.assertEqual((fake.fido_attempts, fake.network_attempts, fake.response_allocations), (1, 1, 1))
        with self.assertRaisesRegex(ProviderDispatchError, "authorization_replayed"):
            fake.retrieve(tx, "connection-1")
        with self.assertRaisesRegex(ProviderDispatchError, "authorization_replayed"):
            fake.reserve("connection-1", 501, self.request, self.parts, self.challenge, "2026-08-03T00:00:03Z")

    def test_chk_m0_10_disconnect_expiry_and_flood_are_pre_authority(self):
        fake = FakeBroker("/tmp/stateful/socket")
        with self.assertRaisesRegex(ProviderDispatchError, "disclosure_declined"):
            fake.decline_disclosure()
        self.assertEqual(fake.status()["pending"], 0)
        tx = fake.reserve("connection-1", 501, self.request, self.parts, self.challenge, "2026-08-03T00:00:01Z")
        fake.disconnect(tx, "connection-1")
        self.assertEqual(fake.reservations[tx].safe_error, "consent_connection_invalid")
        self.assertEqual((fake.fido_attempts, fake.network_attempts, fake.response_allocations), (0, 0, 0))
        stale_req = copy.deepcopy(self.request)
        stale_req["authority"]["nonce"] = "nonce-stale"
        stale_challenge = challenge(stale_req, build_openrouter_body(stale_req, self.parts))
        stale_challenge["transaction_id"] = "transaction-stale"
        stale_challenge["peer_uid"] = 502
        stale_challenge["authority_assertion"]["value"] = "fixture-rsa-sha256-v1:" + "0" * 256
        stale_challenge["authority_assertion"]["value"] = fixture_sign(
            int(FIXTURE_ROOT_PUBLIC_KEY.split(":")[1], 16), ROOT_D,
            signature_input("challenge", stale_challenge),
        )
        tx2 = fake.reserve("connection-2", 502, stale_req, self.parts, stale_challenge, "2026-08-03T00:00:01Z")
        with self.assertRaisesRegex(ProviderDispatchError, "authorization_expired"):
            fake.acknowledge(tx2, "connection-2", {
                "schema_version": 1, "protocol": PROTOCOL, "type": "consent_ack",
                "challenge_sha256": sha256(canonical_json(stale_challenge)),
            }, "2026-08-03T00:03:00Z")
        self.assertEqual(fake.fido_attempts, 0)
        flood = FakeBroker("/tmp/flood/socket")
        for number in range(5):
            chall = challenge(self.request, self.body)
            chall["transaction_id"] = f"transaction-flood-{number}"
            chall["authority_assertion"]["value"] = "fixture-rsa-sha256-v1:" + "0" * 256
            chall["authority_assertion"]["value"] = fixture_sign(
                int(FIXTURE_ROOT_PUBLIC_KEY.split(":")[1], 16), ROOT_D,
                signature_input("challenge", chall),
            )
            if number < 4:
                flood.reserve(f"connection-{number}", 501, self.request, self.parts, chall, "2026-08-03T00:00:01Z")
            else:
                with self.assertRaisesRegex(ProviderDispatchError, "rate_limited"):
                    flood.reserve(f"connection-{number}", 501, self.request, self.parts, chall, "2026-08-03T00:00:01Z")
        self.assertEqual((flood.fido_attempts, flood.network_attempts, flood.response_allocations), (0, 0, 0))

        declined = FakeBroker("/tmp/declined/socket")
        declined_tx = declined.reserve("connection-declined", 501, self.request, self.parts, self.challenge, "2026-08-03T00:00:01Z")
        with self.assertRaisesRegex(ProviderDispatchError, "authorization_declined"):
            declined.acknowledge(declined_tx, "connection-declined", self.ack, "2026-08-03T00:00:02Z", approved=False)
        self.assertEqual((declined.fido_attempts, declined.network_attempts, declined.response_allocations), (1, 0, 0))

        sent = FakeBroker("/tmp/sent/socket")
        tx3 = sent.reserve("connection-sent", 501, self.request, self.parts, self.challenge, "2026-08-03T00:00:01Z")
        sent.acknowledge(tx3, "connection-sent", self.ack, "2026-08-03T00:00:02Z")
        sent.mark_sent(tx3, "connection-sent")
        sent.disconnect(tx3, "connection-sent")
        self.assertEqual(sent.reservations[tx3].safe_error, "provider_result_unknown")
        with self.assertRaises(ProviderDispatchError):
            sent.retrieve(tx3, "connection-sent")

    def test_chk_m0_11_complete_wire_exact_boundary_and_overflow(self):
        parts = [b"x" * MAX_FRAME_BYTES for _ in range(7)] + [b"x" * 1000]
        for _ in range(5):
            req = request(tuple(parts), tuple("user" for _ in parts))
            size = 4 + len(canonical_json(req)) + sum(8 + len(part) for part in parts)
            delta = MAX_REQUEST_BYTES - size
            parts[-1] = parts[-1] + b"x" * delta if delta >= 0 else parts[-1][:delta]
        req = request(tuple(parts), tuple("user" for _ in parts))
        wire = encode_request(req, tuple(parts))
        self.assertEqual(len(wire), MAX_REQUEST_BYTES)
        overflow = list(parts); overflow[-1] += b"x"
        overflow_req = request(tuple(overflow), tuple("user" for _ in overflow))
        with self.assertRaisesRegex(ProviderDispatchError, "bounds_exceeded"):
            encode_request(overflow_req, tuple(overflow))

    def test_chk_m0_12_production_trust_shape_is_distinct_and_fail_closed(self):
        chall = copy.deepcopy(self.challenge)
        chall["authority_assertion"] = {
            "kind": "fido2-es256", "credential_id": "AQ", "authenticator_data": "Ag",
            "client_data_json": "Aw", "signature_der": "BA",
            "user_presence": True, "user_verification": True,
        }
        chall["result_signer"] = {"kind": "ephemeral-es256", "public_key_sec1": "BQ"}
        validate_challenge(chall)
        terminal = copy.deepcopy(self.result)
        terminal["challenge_sha256"] = sha256(canonical_json(chall))
        terminal["authority_assertion_sha256"] = sha256(canonical_json(chall["authority_assertion"]))
        terminal["result_signer_sha256"] = sha256(canonical_json(chall["result_signer"]))
        terminal["signature"] = {"kind": "es256", "signature_der": "Bg"}
        validate_result(terminal)
        with self.assertRaisesRegex(ProviderDispatchError, "authority_unavailable"):
            verify_terminal_result(self.request, chall, self.response, terminal)
        verify_terminal_result(
            self.request, chall, self.response, terminal,
            production_verifier=lambda *_arguments: True,
        )
        with self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
            verify_terminal_result(self.request, self.challenge, self.response, self.result)

    def test_chk_m0_13_reserve_time_window_precedes_capacity_and_uv(self):
        for label, now in (
            ("expired", "2026-08-03T00:02:00Z"),
            ("future", "2026-08-02T23:59:59Z"),
        ):
            fake = FakeBroker(f"/tmp/{label}/socket")
            with self.subTest(label=label), self.assertRaisesRegex(ProviderDispatchError, "authorization_expired"):
                fake.reserve("connection-time", 501, self.request, self.parts, self.challenge, now)
            self.assertEqual(fake.status()["pending"], 0)
            self.assertEqual((fake.fido_attempts, fake.network_attempts, fake.response_allocations), (0, 0, 0))

    def test_chk_m0_14_exchange_repeated_binding_substitutions_reject(self):
        exchange = {
            "schema_version": 1, "protocol": PROTOCOL, "state": "terminal",
            "request": self.request, "request_body_sha256": self.challenge["request_body_sha256"],
            "challenge": self.challenge, "consent_ack": self.ack, "result": self.result,
            "safe_error": None, "consumed": True, "network_attempted": True,
            "response_retrievable": False,
        }
        validate_exchange(exchange)
        mutations = (
            ("body", lambda item: item.__setitem__("request_body_sha256", D)),
            ("scope", lambda item: item["challenge"].__setitem__("scope", {**item["challenge"]["scope"], "run_id": "changed"})),
            ("models", lambda item: item["result"].__setitem__("models", list(reversed(item["result"]["models"])))),
            ("sequence", lambda item: item["result"].__setitem__("sequence", 8)),
            ("chain", lambda item: item["challenge"].__setitem__("prior_chain_digest", D)),
            ("timing", lambda item: item["result"].__setitem__("issued_at", "2026-08-03T00:00:01Z")),
        )
        for label, mutate in mutations:
            item = copy.deepcopy(exchange); mutate(item)
            with self.subTest(label=label), self.assertRaisesRegex(ProviderDispatchError, "terminal_binding_invalid"):
                validate_exchange(item)

    def test_chk_m0_15_result_schema_python_parity(self):
        schema = json.loads(RESULT_SCHEMA.read_text())
        corpus = [self.result]
        for field, value in (
            ("exit_code", 73), ("outcome", "unknown"), ("provider", "attacker"),
        ):
            item = copy.deepcopy(self.result); item[field] = value; corpus.append(item)
        for index, item in enumerate(corpus):
            try:
                validate_result(item)
                python_accepts = True
            except ProviderDispatchError:
                python_accepts = False
            with self.subTest(index=index):
                self.assertEqual(schema_matches(item, schema), python_accepts)

    def test_chk_m0_16_fd3_is_anonymous_pipe_verified_then_single_write(self):
        response_wire = frame64(self.response) + frame32(canonical_json(self.result))
        try:
            saved = os.dup(3)
        except OSError:
            saved = None
        read_fd, write_fd = os.pipe()
        if read_fd == 3:
            replacement = os.dup(read_fd)
            os.close(read_fd)
            read_fd = replacement
        used = set()
        try:
            os.dup2(write_fd, 3)
            if write_fd != 3:
                os.close(write_fd)
            terminal = deliver_verified_fd3(
                3, used, response_wire, self.request, self.challenge,
                fixture_trust=True,
            )
            self.assertEqual(terminal, self.result)
            self.assertEqual(os.read(read_fd, len(self.response)), self.response)
            with self.assertRaisesRegex(ProviderDispatchError, "exchange_state_invalid"):
                deliver_verified_fd3(3, used, response_wire, self.request, self.challenge, fixture_trust=True)
        finally:
            os.close(read_fd)
            try:
                os.close(3)
            except OSError:
                pass
            if saved is not None:
                os.dup2(saved, 3); os.close(saved)
        wrong_read, wrong_write = os.pipe()
        try:
            with self.assertRaisesRegex(ProviderDispatchError, "exchange_state_invalid"):
                validate_fd3(wrong_write, set())
        finally:
            os.close(wrong_read); os.close(wrong_write)
        def reject_at_fd3(source_fd):
            try:
                prior = os.dup(3)
            except OSError:
                prior = None
            try:
                os.dup2(source_fd, 3)
                with self.assertRaisesRegex(ProviderDispatchError, "exchange_state_invalid"):
                    validate_fd3(3, set())
            finally:
                try:
                    os.close(3)
                except OSError:
                    pass
                if prior is not None:
                    os.dup2(prior, 3); os.close(prior)
        with tempfile.TemporaryFile() as regular:
            reject_at_fd3(regular.fileno())
        left, right = socket.socketpair()
        try:
            reject_at_fd3(left.fileno())
        finally:
            left.close(); right.close()


if __name__ == "__main__":
    unittest.main()
