#!/usr/bin/env bash
#
# check-dependencies.sh -- Validate cross-plugin dependencies
#
# Checks that every declared dependency in plugin.json exists,
# satisfies the version constraint, and has the referenced
# capabilities still present on disk.
#
# Usage:
#   ./tools/check-dependencies.sh          # validate all dependencies
#   ./tools/check-dependencies.sh --graph  # output Mermaid dependency diagram
#
# Exit codes:
#   0 -- all dependencies valid
#   1 -- one or more hard dependencies unresolvable

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"

# Colors (disable if not a terminal)
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  RED='\033[0;31m'
  YELLOW='\033[0;33m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  GREEN='' RED='' YELLOW='' BOLD='' RESET=''
fi

# --------------------------------------------------------------------------
# Generate Mermaid dependency graph from plugin.json declarations
# --------------------------------------------------------------------------
generate_graph() {
  cat << 'HEADER'
# Plugin Dependency Graph

Generated by `./tools/check-dependencies.sh --graph`. Do not edit manually.

```mermaid
graph LR
HEADER

  GRAPH_DATA="$PLUGINS_DIR" python3 << 'PYEOF'
import json, os, glob

plugins_dir = os.environ["GRAPH_DATA"]
edges = []

for pj_path in sorted(glob.glob(os.path.join(plugins_dir, "*/.claude-plugin/plugin.json"))):
    with open(pj_path) as f:
        pj = json.load(f)
    name = pj["name"]

    for dep_name in pj.get("dependencies", {}):
        edges.append(f"  {name} --> {dep_name}")

    for dep_name in pj.get("optionalDependencies", {}):
        edges.append(f"  {name} -.-> {dep_name}")

for edge in edges:
    print(edge)
PYEOF

  echo '```'
}

# --------------------------------------------------------------------------
# Semver comparison: check if actual >= required
# --------------------------------------------------------------------------
semver_gte() {
  local actual="$1"   # e.g. "1.5.1"
  local required="$2"  # e.g. "1.2.0" (already stripped of >=)

  ACTUAL="$actual" REQUIRED="$required" python3 << 'PYEOF'
import os, sys

def parse_ver(v):
    parts = v.replace(">=", "").strip().split(".")
    return tuple(int(p) for p in parts)

actual = parse_ver(os.environ["ACTUAL"])
required = parse_ver(os.environ["REQUIRED"])
sys.exit(0 if actual >= required else 1)
PYEOF
}

# --------------------------------------------------------------------------
# Check that referenced capabilities exist on disk
# --------------------------------------------------------------------------
check_capabilities() {
  local source_plugin="$1"
  local dep_plugin="$2"
  local dep_plugin_json="$PLUGINS_DIR/$dep_plugin/.claude-plugin/plugin.json"
  local issues=""

  # Read the dependency plugin's capabilities to know what it declares
  local dep_caps
  dep_caps=$(DEP_PJ="$dep_plugin_json" python3 << 'PYEOF'
import json, os
with open(os.environ["DEP_PJ"]) as f:
    pj = json.load(f)
caps = pj.get("capabilities", {})
# Output skill ids, agent ids, command ids separated by newlines with type prefix
for s in caps.get("skills", []):
    print(f"skill:{s['id']}")
for a in caps.get("agents", []):
    print(f"agent:{a['id']}:{a.get('category','review')}")
for c in caps.get("commands", []):
    print(f"command:{c['id']}")
PYEOF
)

  # Check that each declared capability has a corresponding file
  while IFS= read -r cap_line; do
    [ -z "$cap_line" ] && continue
    local cap_type cap_id cap_category
    cap_type="${cap_line%%:*}"
    local rest="${cap_line#*:}"

    case "$cap_type" in
      skill)
        cap_id="$rest"
        if [ ! -f "$PLUGINS_DIR/$dep_plugin/skills/$cap_id/SKILL.md" ]; then
          issues="$issues\n    MISSING: skill $cap_id (no SKILL.md)"
        fi
        ;;
      agent)
        cap_id="${rest%%:*}"
        cap_category="${rest#*:}"
        if [ ! -f "$PLUGINS_DIR/$dep_plugin/agents/$cap_category/$cap_id.md" ]; then
          issues="$issues\n    MISSING: agent $cap_id in $cap_category/ (no .md file)"
        fi
        ;;
      command)
        cap_id="$rest"
        if [ ! -f "$PLUGINS_DIR/$dep_plugin/commands/$cap_id.md" ]; then
          issues="$issues\n    MISSING: command $cap_id (no .md file)"
        fi
        ;;
    esac
  done <<< "$dep_caps"

  if [ -n "$issues" ]; then
    echo "$issues"
    return 1
  fi
  return 0
}

# --------------------------------------------------------------------------
# Validate all dependencies for one plugin
# --------------------------------------------------------------------------
validate_plugin() {
  local plugin_json="$1"
  local plugin_name
  plugin_name=$(PJSON="$plugin_json" python3 -c "import json,os; print(json.load(open(os.environ['PJSON']))['name'])")

  local any_hard_fail=0
  local dep_type dep_field

  for dep_field in dependencies optionalDependencies; do
    local is_optional=0
    [ "$dep_field" = "optionalDependencies" ] && is_optional=1

    local dep_type_label="required"
    [ "$is_optional" -eq 1 ] && dep_type_label="optional"

    # Extract dependencies as "name|constraint" lines
    local deps
    deps=$(PJSON="$plugin_json" FIELD="$dep_field" python3 << 'PYEOF'
import json, os
with open(os.environ["PJSON"]) as f:
    pj = json.load(f)
deps = pj.get(os.environ["FIELD"], {})
for name, constraint in deps.items():
    print(f"{name}|{constraint}")
PYEOF
)

    [ -z "$deps" ] && continue

    while IFS='|' read -r dep_name constraint; do
      [ -z "$dep_name" ] && continue
      local dep_pj="$PLUGINS_DIR/$dep_name/.claude-plugin/plugin.json"

      # Check plugin exists
      if [ ! -f "$dep_pj" ]; then
        if [ "$is_optional" -eq 1 ]; then
          printf "  ${YELLOW}WARN${RESET}  %-20s -> %-25s  %s (optional, not installed)\n" "$plugin_name" "$dep_name" "$constraint"
        else
          printf "  ${RED}FAIL${RESET}  %-20s -> %-25s  %s (plugin not found)\n" "$plugin_name" "$dep_name" "$constraint"
          any_hard_fail=1
        fi
        continue
      fi

      # Check version
      local dep_version
      dep_version=$(PJSON="$dep_pj" python3 -c "import json,os; print(json.load(open(os.environ['PJSON']))['version'])")
      local ver_constraint="${constraint#>=}"

      if ! semver_gte "$dep_version" "$ver_constraint"; then
        if [ "$is_optional" -eq 1 ]; then
          printf "  ${YELLOW}WARN${RESET}  %-20s -> %-25s  %s (have %s, optional)\n" "$plugin_name" "$dep_name" "$constraint" "$dep_version"
        else
          printf "  ${RED}FAIL${RESET}  %-20s -> %-25s  %s (have %s)\n" "$plugin_name" "$dep_name" "$constraint" "$dep_version"
          any_hard_fail=1
        fi
        continue
      fi

      # Check capabilities exist on disk
      local cap_issues=""
      cap_issues=$(check_capabilities "$plugin_name" "$dep_name" 2>&1) || true

      if [ -n "$cap_issues" ]; then
        if [ "$is_optional" -eq 1 ]; then
          printf "  ${YELLOW}WARN${RESET}  %-20s -> %-25s  %s v%s (capability gaps)%s\n" "$plugin_name" "$dep_name" "$constraint" "$dep_version" "$cap_issues"
        else
          printf "  ${RED}FAIL${RESET}  %-20s -> %-25s  %s v%s (capability gaps)%s\n" "$plugin_name" "$dep_name" "$constraint" "$dep_version" "$cap_issues"
          any_hard_fail=1
        fi
        continue
      fi

      printf "  ${GREEN}OK${RESET}    %-20s -> %-25s  %s v%s\n" "$plugin_name" "$dep_name" "$constraint" "$dep_version"

    done <<< "$deps"
  done

  return $any_hard_fail
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
main() {
  # Handle --graph flag
  if [ "${1:-}" = "--graph" ]; then
    generate_graph
    exit 0
  fi

  printf "\n${BOLD}Dependency Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"

  local any_failed=0
  local checked=0

  for plugin_dir in "$PLUGINS_DIR"/*/; do
    local pj="$plugin_dir/.claude-plugin/plugin.json"
    [ -f "$pj" ] || continue

    # Check if plugin has any dependencies
    local has_deps
    has_deps=$(PJSON="$pj" python3 -c "
import json, os
pj = json.load(open(os.environ['PJSON']))
has = bool(pj.get('dependencies')) or bool(pj.get('optionalDependencies'))
print('yes' if has else 'no')
")

    [ "$has_deps" = "no" ] && continue

    checked=$((checked + 1))
    if ! validate_plugin "$pj"; then
      any_failed=1
    fi
  done

  if [ "$checked" -eq 0 ]; then
    printf "  No plugins declare dependencies.\n"
  fi

  printf "\n${BOLD}%d plugins with dependencies checked${RESET}\n" "$checked"

  if [ "$any_failed" -eq 1 ]; then
    printf "${RED}FAIL: One or more hard dependencies unresolvable${RESET}\n\n"
    exit 1
  else
    printf "${GREEN}PASS: All dependencies satisfied${RESET}\n\n"
    exit 0
  fi
}

main "$@"
