#!/usr/bin/env python3
"""
Generate Codex-visible skill aliases for Claude slash commands.

Claude commands remain canonical:
  - plugins/*/commands/*.md

This script writes generated skill wrappers:
  - plugins/*/skills/<command-name>/SKILL.md

The wrappers let Codex expose command workflows through the skill surface it
already understands, while preserving the original command body as source
material.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PLUGINS_DIR = REPO_ROOT / "plugins"

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n?", re.DOTALL)


def parse_frontmatter(text: str, path: Path) -> tuple[dict[str, str], str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError(f"{path.relative_to(REPO_ROOT)} missing YAML frontmatter")

    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        fields[key.strip()] = value

    return fields, text[match.end() :]


def generated_skill(command_path: Path) -> str:
    fields, body = parse_frontmatter(command_path.read_text(), command_path)

    command_name = fields.get("name", command_path.stem)
    description = fields.get("description", f"Run the /{command_name} command workflow")
    argument_hint = fields.get("argument-hint", "")

    if command_name != command_path.stem:
        raise ValueError(
            f"{command_path.relative_to(REPO_ROOT)} has name={command_name!r}, expected {command_path.stem!r}"
        )

    adapter_notes = [
        f"Expose `/{command_name}` as a workflow entrypoint, not a CLI call. Treat the invoking message as arguments, substitute `$ARGUMENTS`, and follow this protocol in the current Codex harness.",
        "Resolve canonical `plugins/<name>/...` paths under that plugin's host-selected coherent installed bundle, not the consumer repository. Read nested SKILL.md files there and follow them inline when no generic Skill tool exists.",
        "Workflow-specific dispatch takes priority: use required model-router role-dispatch and retain its outputs and receipts. Use native subagents only when that workflow explicitly permits them.",
        "Do not launch another harness solely for its source or cache format. Explicit cross-harness requests and router-selected participant transports remain supported.",
        "Translate Claude tools when needed (`TodoWrite` to `update_plan`; `AskUserQuestion` to `request_user_input` or chat). Report the exact missing path/tool and preserve completed evidence; never manual-substitute required lanes or fabricate receipts.",
    ]

    frontmatter = [
        "---",
        f"name: {command_name}",
        f"description: Codex skill alias for /{command_name}. {description}",
    ]
    if argument_hint:
        frontmatter.append(f"argument-hint: \"{argument_hint}\"")
    frontmatter.append("---")

    return (
        "\n".join(frontmatter)
        + "\n\n"
        + f"# Codex Command Alias: /{command_name}\n\n"
        + "<!-- Generated by tools/generate-codex-command-skills.py; edit the source command instead. -->\n\n"
        + "\n".join(f"- {note}" for note in adapter_notes)
        + "\n\n"
        + "## Command Workflow\n\n"
        + body.strip()
        + "\n"
    )


def expected_files() -> dict[Path, str]:
    files: dict[Path, str] = {}

    for command_path in sorted(PLUGINS_DIR.glob("*/commands/*.md")):
        plugin_dir = command_path.parents[1]
        skill_path = plugin_dir / "skills" / command_path.stem / "SKILL.md"
        files[skill_path] = generated_skill(command_path)

    return files


def write_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        current = path.read_text() if path.exists() else None
        if current != content:
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")


def check_files(files: dict[Path, str]) -> int:
    failures = []
    for path, expected in files.items():
        if not path.exists():
            failures.append(f"missing {path.relative_to(REPO_ROOT)}")
            continue
        if path.read_text() != expected:
            failures.append(f"stale {path.relative_to(REPO_ROOT)}")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        print("FIX  run: ./tools/generate-codex-command-skills.py")
        return 1

    print(f"OK    {len(files)} Codex command skill aliases match command sources")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated command skill aliases are current")
    args = parser.parse_args()

    try:
        files = expected_files()
    except Exception as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    if args.check:
        return check_files(files)

    write_files(files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
