#!/usr/bin/env bash
#
# validate-composition.sh -- Validate plugin composition and generate search index
#
# Checks that cross-plugin references resolve, agent paths exist, and
# the search index matches actual capabilities.
#
# Usage:
#   ./tools/validate-composition.sh                  # composition checks only
#   ./tools/validate-composition.sh --generate-index # regenerate docs/search-index.md
#   ./tools/validate-composition.sh --all            # run all validators (evals + deps + composition)
#
# Exit codes:
#   0 -- all checks pass
#   1 -- one or more checks failed

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"

# Colors
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  RED='\033[0;31m'
  YELLOW='\033[0;33m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  GREEN='' RED='' YELLOW='' BOLD='' RESET=''
fi

# --------------------------------------------------------------------------
# Generate search index from plugin.json capabilities
# --------------------------------------------------------------------------
generate_index() {
  local output_file="$REPO_ROOT/docs/search-index.md"

  PLUGINS_DIR="$PLUGINS_DIR" python3 << 'PYEOF' > "$output_file"
import json, glob, os

plugins_dir = os.environ["PLUGINS_DIR"]
skills = []
agents = []
commands = []

for pj_path in sorted(glob.glob(os.path.join(plugins_dir, "*/.claude-plugin/plugin.json"))):
    with open(pj_path) as f:
        pj = json.load(f)
    name = pj["name"]
    caps = pj.get("capabilities", {})

    for s in caps.get("skills", []):
        triggers = ", ".join(f'"{t}"' for t in s.get("triggers", [])[:5])
        if len(s.get("triggers", [])) > 5:
            triggers += ", ..."
        mcp = ", ".join(s.get("mcpDependencies", [])) or "--"
        tags = ", ".join(s.get("tags", []))
        skills.append((name, s["id"], tags, mcp, triggers))

    for a in caps.get("agents", []):
        tags = ", ".join(a.get("tags", []))
        agents.append((name, a["id"], a.get("category", "review"), tags))

    for c in caps.get("commands", []):
        arg = c.get("argumentHint", "--")
        commands.append((name, c["id"], arg, c["description"]))

print("# Depot Search Index")
print()
print(f"Generated by `./tools/validate-composition.sh --generate-index`. Do not edit manually.")
print()
print(f"**{len(skills)} skills** across {len(set(s[0] for s in skills))} plugins | "
      f"**{len(agents)} agents** ({sum(1 for a in agents if a[2]=='review')} review, "
      f"{sum(1 for a in agents if a[2]=='workflow')} workflow) | "
      f"**{len(commands)} commands**")
print()

# Find by Need
print("## Find by Need")
print()
print("Common questions mapped to the right skill:")
print()
print("| Need | Skill |")
print("|------|-------|")
needs = [
    ('"I need to review my code"', "dm-review/review"),
    ('"What font should I use?"', "design-practice/typography"),
    ('"How do I price this project?"', "project-manager/lt10"),
    ('"Is this accessible?"', "accessibility-compliance/wcag-audit-patterns"),
    ('"Make this sound like me"', "ghostwriter/voice"),
    ('"What do you know about X?"', "ned/ai-memory"),
    ('"What should I work on?"', "project-manager/planner"),
    ('"How do I structure this content?"', "craft-developer/content-modeling"),
    ('"This layout feels wrong"', "design-practice/layout"),
    ('"Set up a new project"', "project-scaffolder/scaffolding"),
    ('"Should I call this profit or surplus?"', "council/decolonial-language"),
    ('"Write a LinkedIn post"', "ghostwriter/social-media"),
    ('"Does this logo work?"', "design-practice/identity"),
    ('"Deploy to the server"', "the-local/server-ops"),
    ('"What should we eat tonight?"', "chef/cooking"),
]
for need, skill in needs:
    print(f"| {need} | {skill} |")
print()

# Skills Index
print("## Skills Index")
print()
print("| Plugin | Skill | Tags | MCP Deps | Triggers |")
print("|--------|-------|------|----------|----------|")
for name, sid, tags, mcp, triggers in skills:
    print(f"| {name} | {sid} | {tags} | {mcp} | {triggers} |")
print()

# Agents Index
print("## Agents Index")
print()
print("| Plugin | Agent | Category | Tags |")
print("|--------|-------|----------|------|")
for name, aid, cat, tags in agents:
    print(f"| {name} | {aid} | {cat} | {tags} |")
print()

# Commands Index
print("## Commands Index")
print()
print("| Plugin | Command | Argument | Description |")
print("|--------|---------|----------|-------------|")
for name, cid, arg, desc in commands:
    print(f"| {name} | /{cid} | {arg} | {desc} |")
PYEOF

  printf "  ${GREEN}OK${RESET}    Generated docs/search-index.md (%d skills, %d agents, %d commands)\n" \
    "$(grep -c '^|' "$output_file" | head -1)" "0" "0"

  # Get actual counts for display
  local skill_count agent_count cmd_count
  skill_count=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('skills',[])) for p in sorted(glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json'))))
print(c)")
  agent_count=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('agents',[])) for p in sorted(glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json'))))
print(c)")
  cmd_count=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('commands',[])) for p in sorted(glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json'))))
print(c)")

  printf "  ${GREEN}OK${RESET}    Search index: %s skills, %s agents, %s commands\n" "$skill_count" "$agent_count" "$cmd_count"
}

# --------------------------------------------------------------------------
# Check that agent references in dm-review SKILL.md resolve
# --------------------------------------------------------------------------
check_agent_references() {
  local skill_file="$PLUGINS_DIR/dm-review/skills/review/SKILL.md"
  local any_failed=0

  if [ ! -f "$skill_file" ]; then
    printf "  ${YELLOW}WARN${RESET}  dm-review SKILL.md not found -- skipping agent reference check\n"
    return 0
  fi

  # Extract agent file paths from the SKILL.md agent selection table
  local agent_paths
  agent_paths=$(grep -oE 'plugins/[a-z-]+/agents/(review|workflow)/[a-z0-9-]+\.md' "$skill_file" | sort -u)

  while IFS= read -r agent_path; do
    [ -z "$agent_path" ] && continue
    local full_path="$REPO_ROOT/$agent_path"
    if [ -f "$full_path" ]; then
      printf "  ${GREEN}OK${RESET}    %s\n" "$agent_path"
    else
      printf "  ${RED}FAIL${RESET}  %s (file not found)\n" "$agent_path"
      any_failed=1
    fi
  done <<< "$agent_paths"

  return $any_failed
}

# --------------------------------------------------------------------------
# Check that companion skill references in commands resolve
# --------------------------------------------------------------------------
check_companion_skills() {
  local any_failed=0

  # Search all command .md files for companion skill loading patterns
  local refs
  refs=$(grep -rn 'skill from.*plugin\|Load.*skill\|companion skill' "$PLUGINS_DIR"/*/commands/*.md 2>/dev/null || true)

  if [ -z "$refs" ]; then
    printf "  ${GREEN}OK${RESET}    No companion skill references found in commands\n"
    return 0
  fi

  # Extract plugin references from sprint-plan.md (the primary user of this pattern)
  local sprint_plan="$PLUGINS_DIR/project-manager/commands/sprint-plan.md"
  if [ -f "$sprint_plan" ]; then
    # Extract "from <plugin> plugin" patterns
    local referenced_plugins
    referenced_plugins=$(grep -oE 'from [a-z-]+ plugin' "$sprint_plan" | sed 's/from //;s/ plugin//' | sort -u)

    while IFS= read -r plugin_name; do
      [ -z "$plugin_name" ] && continue
      if [ -d "$PLUGINS_DIR/$plugin_name" ]; then
        printf "  ${GREEN}OK${RESET}    sprint-plan companion: %s (installed)\n" "$plugin_name"
      else
        printf "  ${RED}FAIL${RESET}  sprint-plan companion: %s (not installed)\n" "$plugin_name"
        any_failed=1
      fi
    done <<< "$referenced_plugins"
  fi

  return $any_failed
}

# --------------------------------------------------------------------------
# Check search index freshness
# --------------------------------------------------------------------------
check_index_freshness() {
  local index_file="$REPO_ROOT/docs/search-index.md"

  if [ ! -f "$index_file" ]; then
    printf "  ${YELLOW}WARN${RESET}  docs/search-index.md not found -- run with --generate-index\n"
    return 0
  fi

  # Count rows in each table section
  # Use python3 for reliable section parsing
  local counts
  counts=$(INDEX_FILE="$index_file" python3 << 'PYEOF'
import os, re
with open(os.environ["INDEX_FILE"]) as f:
    content = f.read()
sections = re.split(r'^## ', content, flags=re.MULTILINE)
skills = agents = commands = 0
for s in sections:
    rows = [l for l in s.split('\n') if l.startswith('|') and not l.startswith('|--') and not l.startswith('| Plugin') and not l.startswith('| Need')]
    if s.startswith('Skills Index'):
        skills = len(rows)
    elif s.startswith('Agents Index'):
        agents = len(rows)
    elif s.startswith('Commands Index'):
        commands = len(rows)
print(f"{skills} {agents} {commands}")
PYEOF
)
  local index_skills index_agents index_commands
  read -r index_skills index_agents index_commands <<< "$counts"

  # Count actual capabilities
  local actual_skills actual_agents actual_commands
  actual_skills=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('skills',[])) for p in glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json')))
print(c)")
  actual_agents=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('agents',[])) for p in glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json')))
print(c)")
  actual_commands=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
c = sum(len(json.load(open(p)).get('capabilities',{}).get('commands',[])) for p in glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json')))
print(c)")

  local stale=0
  if [ "$index_skills" -ne "$actual_skills" ]; then
    printf "  ${YELLOW}WARN${RESET}  Skills: index has %s, actual is %s\n" "$index_skills" "$actual_skills"
    stale=1
  fi
  if [ "$index_agents" -ne "$actual_agents" ]; then
    printf "  ${YELLOW}WARN${RESET}  Agents: index has %s, actual is %s\n" "$index_agents" "$actual_agents"
    stale=1
  fi
  if [ "$index_commands" -ne "$actual_commands" ]; then
    printf "  ${YELLOW}WARN${RESET}  Commands: index has %s, actual is %s\n" "$index_commands" "$actual_commands"
    stale=1
  fi

  if [ "$stale" -eq 1 ]; then
    printf "  ${YELLOW}WARN${RESET}  Search index is stale -- regenerate with: ./tools/validate-composition.sh --generate-index\n"
  else
    printf "  ${GREEN}OK${RESET}    Search index is current (%s skills, %s agents, %s commands)\n" "$actual_skills" "$actual_agents" "$actual_commands"
  fi

  return 0
}

# --------------------------------------------------------------------------
# Run all validators
# --------------------------------------------------------------------------
run_all() {
  local any_failed=0

  printf "\n${BOLD}1/3: Description Evals${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if "$SCRIPT_DIR/eval-descriptions.sh"; then
    :
  else
    any_failed=1
  fi

  printf "\n${BOLD}2/3: Dependency Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if "$SCRIPT_DIR/check-dependencies.sh"; then
    :
  else
    any_failed=1
  fi

  printf "\n${BOLD}3/3: Composition Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if run_composition_checks; then
    :
  else
    any_failed=1
  fi

  if [ "$any_failed" -eq 1 ]; then
    printf "\n${RED}FAIL: One or more validators reported issues${RESET}\n\n"
    exit 1
  else
    printf "\n${GREEN}PASS: All validators passed${RESET}\n\n"
    exit 0
  fi
}

# --------------------------------------------------------------------------
# Composition checks (the default mode)
# --------------------------------------------------------------------------
run_composition_checks() {
  local any_failed=0

  printf "${BOLD}Composition Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"

  printf "${BOLD}Agent references (dm-review orchestration):${RESET}\n"
  if ! check_agent_references; then
    any_failed=1
  fi

  printf "\n${BOLD}Companion skill references:${RESET}\n"
  if ! check_companion_skills; then
    any_failed=1
  fi

  printf "\n${BOLD}Search index freshness:${RESET}\n"
  check_index_freshness

  printf "\n"
  if [ "$any_failed" -eq 1 ]; then
    printf "${RED}FAIL: Broken composition references found${RESET}\n\n"
    return 1
  else
    printf "${GREEN}PASS: All composition references valid${RESET}\n\n"
    return 0
  fi
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
main() {
  case "${1:-}" in
    --generate-index)
      printf "\n${BOLD}Generating Search Index${RESET}\n"
      printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
      generate_index
      printf "\n${GREEN}Done.${RESET}\n\n"
      ;;
    --all)
      run_all
      ;;
    "")
      run_composition_checks
      exit $?
      ;;
    *)
      echo "Usage: $0 [--generate-index | --all]" >&2
      exit 1
      ;;
  esac
}

main "$@"
