#!/usr/bin/env bash
#
# validate-composition.sh -- Validate plugin composition and generate search index
#
# Checks that cross-plugin references resolve, agent paths exist, and
# the search index matches actual capabilities.
#
# Usage:
#   ./tools/validate-composition.sh                  # composition checks only
#   ./tools/validate-composition.sh --generate-index # regenerate docs/search-index.md
#   ./tools/validate-composition.sh --all            # run all validators (evals + deps + composition)
#
# Exit codes:
#   0 -- all checks pass
#   1 -- one or more checks failed

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"

# Colors
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  RED='\033[0;31m'
  YELLOW='\033[0;33m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  GREEN='' RED='' YELLOW='' BOLD='' RESET=''
fi

# --------------------------------------------------------------------------
# Generate search index from plugin.json capabilities
# --------------------------------------------------------------------------
generate_index() {
  local output_file="$REPO_ROOT/docs/search-index.md"

  PLUGINS_DIR="$PLUGINS_DIR" python3 << 'PYEOF' > "$output_file"
import json, glob, os

plugins_dir = os.environ["PLUGINS_DIR"]
skills = []
agents = []
commands = []

for pj_path in sorted(glob.glob(os.path.join(plugins_dir, "*/.claude-plugin/plugin.json"))):
    with open(pj_path) as f:
        pj = json.load(f)
    name = pj["name"]
    caps = pj.get("capabilities", {})

    for s in caps.get("skills", []):
        triggers = ", ".join(f'"{t}"' for t in s.get("triggers", [])[:5])
        if len(s.get("triggers", [])) > 5:
            triggers += ", ..."
        mcp = ", ".join(s.get("mcpDependencies", [])) or "--"
        tags = ", ".join(s.get("tags", []))
        skills.append((name, s["id"], tags, mcp, triggers))

    for a in caps.get("agents", []):
        tags = ", ".join(a.get("tags", []))
        agents.append((name, a["id"], a.get("category", "review"), tags))

    for c in caps.get("commands", []):
        arg = c.get("argumentHint", "--")
        commands.append((name, c["id"], arg, c["description"]))

print("# Depot Search Index")
print()
print(f"Generated by `./tools/validate-composition.sh --generate-index`. Do not edit manually.")
print()
print(f"**{len(skills)} skills** across {len(set(s[0] for s in skills))} plugins | "
      f"**{len(agents)} agents** ({sum(1 for a in agents if a[2]=='review')} review, "
      f"{sum(1 for a in agents if a[2]=='workflow')} workflow) | "
      f"**{len(commands)} commands**")
print()

# Find by Need
print("## Find by Need")
print()
print("Common questions mapped to the right skill:")
print()
print("| Need | Skill |")
print("|------|-------|")
needs = [
    ('"I need to review my code"', "dm-review/review"),
    ('"What font should I use?"', "design-practice/typography"),
    ('"How do I price this project?"', "project-manager/lt10"),
    ('"Is this accessible?"', "accessibility-compliance/wcag-audit-patterns"),
    ('"Make this sound like me"', "ghostwriter/voice"),
    ('"What do you know about X?"', "ned/ai-memory"),
    ('"What should I work on?"', "project-manager/planner"),
    ('"How do I structure this content?"', "craft-developer/content-modeling"),
    ('"This layout feels wrong"', "design-practice/layout"),
    ('"Set up a new project"', "project-scaffolder/scaffolding"),
    ('"Should I call this profit or surplus?"', "council/decolonial-language"),
    ('"Write a LinkedIn post"', "ghostwriter/social-media"),
    ('"Does this logo work?"', "design-practice/identity"),
    ('"Deploy to the server"', "the-local/server-ops"),
    ('"What should we eat tonight?"', "chef/cooking"),
]
for need, skill in needs:
    print(f"| {need} | {skill} |")
print()

# Skills Index
print("## Skills Index")
print()
print("| Plugin | Skill | Tags | MCP Deps | Triggers |")
print("|--------|-------|------|----------|----------|")
for name, sid, tags, mcp, triggers in skills:
    print(f"| {name} | {sid} | {tags} | {mcp} | {triggers} |")
print()

# Agents Index
print("## Agents Index")
print()
print("| Plugin | Agent | Category | Tags |")
print("|--------|-------|----------|------|")
for name, aid, cat, tags in agents:
    print(f"| {name} | {aid} | {cat} | {tags} |")
print()

# Commands Index
print("## Commands Index")
print()
print("| Plugin | Command | Argument | Description |")
print("|--------|---------|----------|-------------|")
for name, cid, arg, desc in commands:
    print(f"| {name} | /{cid} | {arg} | {desc} |")
PYEOF

  # Get actual counts for display (single python3 call)
  local counts
  counts=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
pjs = [json.load(open(p)).get('capabilities',{}) for p in sorted(glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json')))]
print(sum(len(c.get('skills',[])) for c in pjs), sum(len(c.get('agents',[])) for c in pjs), sum(len(c.get('commands',[])) for c in pjs))")
  local skill_count agent_count cmd_count
  read -r skill_count agent_count cmd_count <<< "$counts"

  printf "  ${GREEN}OK${RESET}    Generated search index: %s skills, %s agents, %s commands\n" "$skill_count" "$agent_count" "$cmd_count"
}

# --------------------------------------------------------------------------
# Check that agent references in dm-review SKILL.md resolve
# --------------------------------------------------------------------------
check_agent_references() {
  local skill_file="$PLUGINS_DIR/dm-review/skills/review/SKILL.md"
  local any_failed=0

  if [ ! -f "$skill_file" ]; then
    printf "  ${YELLOW}WARN${RESET}  dm-review SKILL.md not found -- skipping agent reference check\n"
    return 0
  fi

  # Extract agent file paths from the SKILL.md agent selection table
  local agent_paths
  agent_paths=$(grep -oE 'plugins/[a-z-]+/agents/(review|workflow)/[a-z0-9-]+\.md' "$skill_file" | sort -u)

  while IFS= read -r agent_path; do
    [ -z "$agent_path" ] && continue
    local full_path="$REPO_ROOT/$agent_path"
    if [ -f "$full_path" ]; then
      printf "  ${GREEN}OK${RESET}    %s\n" "$agent_path"
    else
      printf "  ${RED}FAIL${RESET}  %s (file not found)\n" "$agent_path"
      any_failed=1
    fi
  done <<< "$agent_paths"

  return $any_failed
}

# --------------------------------------------------------------------------
# Check that companion skill references in commands resolve
# --------------------------------------------------------------------------
check_companion_skills() {
  local any_failed=0

  # Find all command files with companion skill references
  local files_with_refs
  files_with_refs=$(grep -rl 'from.*plugin\|companion skill' "$PLUGINS_DIR"/*/commands/*.md 2>/dev/null || true)

  if [ -z "$files_with_refs" ]; then
    printf "  ${GREEN}OK${RESET}    No companion skill references found in commands\n"
    return 0
  fi

  # Check each command file that references companion plugins
  while IFS= read -r cmd_file; do
    [ -z "$cmd_file" ] && continue
    local cmd_name
    cmd_name=$(basename "$cmd_file" .md)

    local referenced_plugins
    referenced_plugins=$(grep -oE 'from [a-z-]+ plugin' "$cmd_file" | sed 's/from //;s/ plugin//' | sort -u)

    while IFS= read -r plugin_name; do
      [ -z "$plugin_name" ] && continue
      if [ -d "$PLUGINS_DIR/$plugin_name" ]; then
        printf "  ${GREEN}OK${RESET}    %s companion: %s (installed)\n" "$cmd_name" "$plugin_name"
      else
        printf "  ${RED}FAIL${RESET}  %s companion: %s (not installed)\n" "$cmd_name" "$plugin_name"
        any_failed=1
      fi
    done <<< "$referenced_plugins"
  done <<< "$files_with_refs"

  return $any_failed
}



# --------------------------------------------------------------------------
# Check marketplace.json versions match plugin.json versions
# --------------------------------------------------------------------------
check_marketplace_versions() {
  local marketplace_file="$REPO_ROOT/.claude-plugin/marketplace.json"
  local any_failed=0

  if [ ! -f "$marketplace_file" ]; then
    printf "  ${YELLOW}WARN${RESET}  .claude-plugin/marketplace.json not found -- skipping version sync check\n"
    return 0
  fi

  local result
  result=$(PLUGINS_DIR="$PLUGINS_DIR" MARKETPLACE="$marketplace_file" python3 << 'PYEOF'
import json, os

plugins_dir = os.environ["PLUGINS_DIR"]
marketplace_path = os.environ["MARKETPLACE"]

with open(marketplace_path) as f:
    marketplace = json.load(f)

mismatches = []
ok_count = 0

for entry in marketplace.get("plugins", []):
    name = entry["name"]
    market_ver = entry.get("version", "NONE")
    plugin_json = os.path.join(plugins_dir, name, ".claude-plugin", "plugin.json")

    if not os.path.exists(plugin_json):
        mismatches.append((name, market_ver, "NOT FOUND"))
        continue

    with open(plugin_json) as f:
        actual_ver = json.load(f).get("version", "NONE")

    if market_ver != actual_ver:
        mismatches.append((name, market_ver, actual_ver))
    else:
        ok_count += 1

# Output: first line is ok count, then mismatches
print(f"OK:{ok_count}")
for name, market_ver, actual_ver in mismatches:
    print(f"MISMATCH:{name}:{market_ver}:{actual_ver}")
PYEOF
)

  local ok_count=0
  while IFS= read -r line; do
    case "$line" in
      OK:*)
        ok_count="${line#OK:}"
        ;;
      MISMATCH:*)
        local details="${line#MISMATCH:}"
        local plugin_name market_ver actual_ver
        IFS=: read -r plugin_name market_ver actual_ver <<< "$details"
        printf "  ${RED}FAIL${RESET}  %s: marketplace.json=%s but plugin.json=%s\n" "$plugin_name" "$market_ver" "$actual_ver"
        any_failed=1
        ;;
    esac
  done <<< "$result"

  if [ "$any_failed" -eq 0 ]; then
    printf "  ${GREEN}OK${RESET}    All %s plugin versions in sync (marketplace.json == plugin.json)\n" "$ok_count"
  else
    printf "  ${YELLOW}FIX${RESET}   Update the version field in .claude-plugin/marketplace.json to match\n"
  fi

  return $any_failed
}

# --------------------------------------------------------------------------
# Check search index freshness
# --------------------------------------------------------------------------
check_index_freshness() {
  local index_file="$REPO_ROOT/docs/search-index.md"

  if [ ! -f "$index_file" ]; then
    printf "  ${YELLOW}WARN${RESET}  docs/search-index.md not found -- run with --generate-index\n"
    return 0
  fi

  # Count rows in each table section
  # Use python3 for reliable section parsing
  local counts
  counts=$(INDEX_FILE="$index_file" python3 << 'PYEOF'
import os, re
with open(os.environ["INDEX_FILE"]) as f:
    content = f.read()
sections = re.split(r'^## ', content, flags=re.MULTILINE)
skills = agents = commands = 0
for s in sections:
    rows = [l for l in s.split('\n') if l.startswith('|') and not l.startswith('|--') and not l.startswith('| Plugin') and not l.startswith('| Need')]
    if s.startswith('Skills Index'):
        skills = len(rows)
    elif s.startswith('Agents Index'):
        agents = len(rows)
    elif s.startswith('Commands Index'):
        commands = len(rows)
print(f"{skills} {agents} {commands}")
PYEOF
)
  local index_skills index_agents index_commands
  read -r index_skills index_agents index_commands <<< "$counts"

  # Count actual capabilities (single python3 call)
  local actual_counts
  actual_counts=$(PLUGINS_DIR="$PLUGINS_DIR" python3 -c "
import json, glob, os
pjs = [json.load(open(p)).get('capabilities',{}) for p in glob.glob(os.path.join(os.environ['PLUGINS_DIR'],'*/.claude-plugin/plugin.json'))]
print(sum(len(c.get('skills',[])) for c in pjs), sum(len(c.get('agents',[])) for c in pjs), sum(len(c.get('commands',[])) for c in pjs))")
  local actual_skills actual_agents actual_commands
  read -r actual_skills actual_agents actual_commands <<< "$actual_counts"

  local stale=0
  if [ "$index_skills" -ne "$actual_skills" ]; then
    printf "  ${YELLOW}WARN${RESET}  Skills: index has %s, actual is %s\n" "$index_skills" "$actual_skills"
    stale=1
  fi
  if [ "$index_agents" -ne "$actual_agents" ]; then
    printf "  ${YELLOW}WARN${RESET}  Agents: index has %s, actual is %s\n" "$index_agents" "$actual_agents"
    stale=1
  fi
  if [ "$index_commands" -ne "$actual_commands" ]; then
    printf "  ${YELLOW}WARN${RESET}  Commands: index has %s, actual is %s\n" "$index_commands" "$actual_commands"
    stale=1
  fi

  if [ "$stale" -eq 1 ]; then
    printf "  ${YELLOW}WARN${RESET}  Search index is stale -- regenerate with: ./tools/validate-composition.sh --generate-index\n"
  else
    printf "  ${GREEN}OK${RESET}    Search index is current (%s skills, %s agents, %s commands)\n" "$actual_skills" "$actual_agents" "$actual_commands"
  fi

  return 0
}

# --------------------------------------------------------------------------
# Run all validators
# --------------------------------------------------------------------------
run_all() {
  local any_failed=0

  printf "\n${BOLD}1/3: Description Evals${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if "$SCRIPT_DIR/eval-descriptions.sh"; then
    :
  else
    any_failed=1
  fi

  printf "\n${BOLD}2/3: Dependency Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if "$SCRIPT_DIR/check-dependencies.sh"; then
    :
  else
    any_failed=1
  fi

  printf "\n${BOLD}3/3: Composition Validation${RESET}\n"
  printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  if run_composition_checks --no-header; then
    :
  else
    any_failed=1
  fi

  if [ "$any_failed" -eq 1 ]; then
    printf "\n${RED}FAIL: One or more validators reported issues${RESET}\n\n"
    exit 1
  else
    printf "\n${GREEN}PASS: All validators passed${RESET}\n\n"
    exit 0
  fi
}

# --------------------------------------------------------------------------
# Check SKILL.md frontmatter integrity
#
# A recurring corruption pattern collapses YAML frontmatter into a Markdown
# heading. The signature: file starts with `---` (opening delimiter) but the
# closing `---` is missing within the first 100 lines, AND line 3 starts with
# `## name:` -- the `name:` and `description:` keys got fused into a heading.
#
# Detection is one-pass and deterministic. False positives are essentially
# zero because no legitimate SKILL.md has `## name:` on line 3.
# --------------------------------------------------------------------------
check_skill_frontmatter() {
  local any_failed=0
  local checked=0
  local plugins_dir="$REPO_ROOT/plugins"

  while IFS= read -r -d '' skill_file; do
    checked=$((checked + 1))
    local rel="${skill_file#$REPO_ROOT/}"

    # Smoking gun #1: file does not start with ---
    if [ "$(head -1 "$skill_file")" != "---" ]; then
      printf "  ${RED}FAIL${RESET}  %s: missing opening '---' frontmatter delimiter on line 1\n" "$rel"
      any_failed=1
      continue
    fi

    # Smoking gun #2: fewer than 2 '---' delimiter lines in the first 100 lines
    local delim_count
    delim_count=$(head -100 "$skill_file" | grep -c '^---$')
    if [ "$delim_count" -lt 2 ]; then
      printf "  ${RED}FAIL${RESET}  %s: only %s '---' delimiter(s) in first 100 lines (frontmatter must have opening AND closing)\n" "$rel" "$delim_count"
      any_failed=1
      continue
    fi

    # Smoking gun #3: '## name:' as a heading inside what should be frontmatter
    # (canonical corruption signature: keys fused into a Markdown heading)
    if head -10 "$skill_file" | grep -qE '^##[[:space:]]+name:'; then
      printf "  ${RED}FAIL${RESET}  %s: corruption pattern detected -- '## name:' heading found in first 10 lines (frontmatter destroyed)\n" "$rel"
      any_failed=1
      continue
    fi
  done < <(find "$plugins_dir" -name "SKILL.md" -path "*/skills/*" -print0 2>/dev/null)

  if [ "$any_failed" -eq 0 ]; then
    printf "  ${GREEN}OK${RESET}    %s SKILL.md files have valid frontmatter\n" "$checked"
  else
    printf "  ${YELLOW}FIX${RESET}   Restore via: git checkout HEAD -- <path>  (then verify the description fields are intact before committing)\n"
  fi

  return $any_failed
}

# --------------------------------------------------------------------------
# Composition checks (the default mode)
# --------------------------------------------------------------------------
run_composition_checks() {
  local any_failed=0
  local skip_header="${1:-}"

  if [ "$skip_header" != "--no-header" ]; then
    printf "${BOLD}Composition Validation${RESET}\n"
    printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
  fi

  printf "${BOLD}Agent references (dm-review orchestration):${RESET}\n"
  if ! check_agent_references; then
    any_failed=1
  fi

  printf "\n${BOLD}Companion skill references:${RESET}\n"
  if ! check_companion_skills; then
    any_failed=1
  fi

  printf "\n${BOLD}Marketplace version sync:${RESET}\n"
  if ! check_marketplace_versions; then
    any_failed=1
  fi

  printf "\n${BOLD}SKILL.md frontmatter integrity:${RESET}\n"
  if ! check_skill_frontmatter; then
    any_failed=1
  fi

  printf "\n${BOLD}Search index freshness:${RESET}\n"
  check_index_freshness

  printf "\n"
  if [ "$any_failed" -eq 1 ]; then
    printf "${RED}FAIL: Broken composition references found${RESET}\n\n"
    return 1
  else
    printf "${GREEN}PASS: All composition references valid${RESET}\n\n"
    return 0
  fi
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
main() {
  case "${1:-}" in
    --generate-index)
      printf "\n${BOLD}Generating Search Index${RESET}\n"
      printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
      generate_index
      printf "\n${GREEN}Done.${RESET}\n\n"
      ;;
    --all)
      run_all
      ;;
    "")
      run_composition_checks
      exit $?
      ;;
    *)
      echo "Usage: $0 [--generate-index | --all]" >&2
      exit 1
      ;;
  esac
}

main "$@"
